disabled_rules:
  - object_literal
  - force_try
  - file_name
  - function_parameter_count
  - weak_delegate
  - unneeded_override
  - redundant_discardable_let
  - unused_optional_binding
  - nslocalizedstring_require_bundle
  - nslocalizedstring_key
  - legacy_objc_type
  - discouraged_optional_boolean
  - control_statement
  - lower_acl_than_parent
  - force_cast
  - direct_return
  - anonymous_argument_in_multiline_closure
  - prohibited_interface_builder
  - strong_iboutlet
  - redundant_type_annotation
  - attributes
  - private_outlet
  - private_action
  - trailing_whitespace
  - anyobject_protocol
  - closure_body_length
  - conditional_returns_on_newline
  - convenience_type
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - file_types_order
  - force_unwrapping
  - function_default_parameter_at_end
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - inert_defer
  - missing_docs
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - no_extension_access_modifier
  - no_fallthrough_only
  - no_grouping_extension
  - no_magic_numbers
  - prefer_nimble
  - prefer_self_in_static_references
  - prefixed_toplevel_constant
  - redundant_self_in_closure
  - required_deinit
  - self_binding
  - sorted_enum_cases
  - strict_fileprivate
  - superfluous_else
  - switch_case_on_newline
  - todo
  - trailing_closure
  - type_contents_order
  - unused_capture_list
  - vertical_whitespace_between_cases
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

identifier_name:
    min_length:
        warning: 1
        error: 1
    excluded:
        - id
    allowed_symbols: "_"

line_length:
    warning: 250
    error: 2000
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    ignores_interpolated_strings: true
function_body_length:
    warning: 300
    error: 500
type_body_length:
    warning: 600
    error: 1500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 50
    error: 70
nesting:
    type_level: 5
reporter: "xcode"
